spring:
    application:
      name: fitness-metrics-service
    datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitness-metrics}
      username: ${SPRING_DATASOURCE_USERNAME:fitness-metrics}
      password: ${SPRING_DATASOURCE_PASSWORD:fitiz-fitness-metrics}
      driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
server:
    port: 9872

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8710/eureka/}
